---
title: "Planning"
format: html
---


# Slide 1

SFC amazing, whether 20 markers or 60, ability to rapidly acquire millions of cells in minutes. expanding our understanding human immunology, potential for biologica characterization rarer subsets, particularly invaluable for clinical specimens limited biospecimen. 

# Slide 2
Immense potential, with elephants in the room. Uncertainty ~ marker "abundances", everything affect, tandem degradagtion, non-speicifc, af variation, coexpression. Caution in attributing to biology what could be technical artefat in these large panels. 

# Slide 3

While if you are interested in a single cell population, the analysis remains essentially the same, there is one area I have constantly grappled with over my PhD. Namely, if we acquired 7 million cells to characterize 100 of our rare population, what is occuring in the rest of the cells. Especially if for a rare clinical cohort. 

# Slide 4

Unsupervised analytical methods have often been touted as the solution, but in their current implementation, are they fully leveraging the entirety of our unique datasets? Or are they confined to skimming the surface. Similarly, we cluster, is the statistical test even biologically relavent if three distinct groups of cells ended smooshed together. And if our datasets have MFI batch effects, how reliable would they perform. 

# Slide 5

Because at the end of the day, when it's 3 AM, I step back. On a spectrum, our discussions about clusters and metaclusters revolve about where we draw the lines. On one end every cell is in a cluster with itself. On the other everything is in the same cluster. 

# Slide 6

Every panel, depending on our markers, has an ability to define cell populations that are present up to a certain point. And various groups have previous implementations of trying to corral cells of these phenotypes for biological insight. 

# Slide 7

At the end of the day, I want to leverage the clearest insight out of my panel. Just like I make my single-color controls each time because I don't want to spend hours after the fact trying to make things work, I don't see the point of clustering only to spend hours laboriously re-glue-ing things back together. (too much, tone it back?)

# Slide 8

We are working with a cohort of malawian infants, well stratefied HIV and ART exposure.

- Cryopreserved
- 0,4,9 months
- Using a 32-fluorophore panel, intranuclear, high AB co-expression markers for cytokines and AIMs. 
- Rested 6 hours, stimulated w PPD, SEB, w/o golgi for 3, with golgi for 9 hours. 
- Acquired 5-laser cytek Aurora passed QC

# Slide 9
- Our analysis pipeline has evolved since our previous papers. Previously mainly FlowJo, increasingly in R, with skeleton elements of Rust taking over performance behind the scenes. However, still traditional cytometrist, so interconversion is critical. 

- Pre-Unmixing, we are using Luciernaga to screen our unmixing control signatures. Visualizing across time, pinpoint bad controls and remove. Similar approach for which samples are getting beads vs. cells. 

- Screening with PeacoQC, originally R version, but James Moyihan's Rust implementation is sweet!

- Automated Gating to Cell Subsets: openCyto (mainly mindensity with a lot of gate_range arguments), but also flowMagic (both our own GatingSet implementation, but with sebastianos last update going his route). 

- Using the old Cytoverse docker container to go from a GatingSet back to FlowJo v.10 workspace to allow for corrections by traditional flow cytometrist. 

- Coereba: newer R packages. Main idea is on a per-cell basis defining a identity column that encompasses all the manual gated definitions for every marker interest. This then travels and can be used to cross-check assumptions for the dimensionality visualizations

- Run openCyto mindensity, check, constrain. We interactively update the placements via a Shiny App. Then Coereba is run

- Once column is incorporated, we can normalize. Trying CytoNorm and CyCombine, using a single-donor thaw specimen for each experiment. If anyone has suggestions, open, since so far results have been mixed. Typically applying at the cell node level rather than the whole file. 

- Point, choosing to either downsample for larger pops, or concatenate entire population.

- Dimensionality Viz - UMAP or PaCMAP via Python

- Gate on "clusters/islands/pick-your-terminology", process of CoerebaID incorporation is reversible, and we retrieve/rederrive the proportion cells from each donor that ended up in the area that were positive or negative for each marker. 

- Likewise, these outputs get incorporated into Bioconductor SummarizedExperiment object, allowing for filtering, renumeration, and passing to downstream statistical analysis packages. 

- As suspected, not all dimensionality methods are separating down to pure populations when visualized. 

- However, we can quickly iterate out the marker expression plots for an individual specimen. 

# Slide 10

- Enough to anger both sides of the automated gating vs. unsupervised clustering camps
- Strong emphasis at the moment on exploratory data analysis. 
- No stand at this point on where to draw the clustering continuum 
- Individual nodes are too noisy for standard tests
- Off-target uses are those that are fascinating, more programmatic outputs that not have in typical flow cytometry analysis

# Slide 11
- Identify freezer burned specimens otherwise would have included. 
- Overnight staining vs. day of, differential population loss?